name: Pull Request Labels

on:
  pull_request:
    types: closed

jobs:
  my_job:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
    - run: exit 1
#    - uses: mheap/github-action-required-labels@v5
#      with:
#        mode: exactly
#        count: 0
#        labels: "do not merge"
